name: aiu_project
description: "A new Flutter project."


publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter

  
  cupertino_icons: ^1.0.8
  firebase_core: ^3.6.0
  firebase_auth: ^5.3.1
  cloud_firestore: ^5.4.4
  get: ^4.6.6
  url_launcher: ^6.3.1
  intl: ^0.19.0
  http: ^1.2.2
  get_storage: ^2.1.1
  logger: ^2.4.0
  iconsax: ^0.0.8
  smooth_page_indicator: ^1.2.0+3
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  uuid: ^4.5.1
  animate_do: ^3.3.4
  panara_dialogs: ^0.1.5
  lottie: ^3.1.3
  ftoast: ^2.0.0
  flutter_slider_drawer: ^2.1.3
  flutter_cupertino_date_picker_fork: ^1.0.7
  fluttertoast: ^8.2.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.13
  hive_generator: ^2.0.1

  
  flutter_lints: ^4.0.0


flutter:

  
  uses-material-design: true

  
  assets:
    - assets/
    - assets/fonts/
    - assets/icons/
    - assets/logos/
    - assets/images/
    - assets/images/on_boarding_images/
    - assets/images/animations/

  
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Light.ttf
          weight: 300
        - asset: assets/fonts/Poppins-Regular.ttf
          weight: 400
        - asset: assets/fonts/Poppins-Italic.ttf
          style: italic
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-MediumItalic.ttf
          weight: 500
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 800
  
  
  
