name: aiu_project
description: "A new Flutter project."


publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  animate_do: ^3.3.4
  cloud_firestore: ^5.4.4
  crystal_navigation_bar: ^1.0.1
  dropdown_button2: ^2.3.9
  firebase_auth: ^5.3.1
  firebase_core: ^3.6.0
  fl_chart: ^0.69.0
  flutter:
    sdk: flutter
  flutter_local_notifications: ^18.0.0
  flutter_screenutil: ^5.9.3
  flutter_slider_drawer: ^2.1.3
  flutter_svg: ^2.0.14
  flutter_timezone: ^3.0.1
  ftoast: ^2.0.0
  get: ^4.6.6
  get_storage: ^2.1.1
  google_fonts: ^6.2.1
  hive_flutter: ^1.1.0
  http: ^1.2.2
  iconsax: ^0.0.8
  image_picker: ^1.1.2
  intl: ^0.19.0
  logger: ^2.4.0
  lottie: ^3.1.3
  panara_dialogs: ^0.1.5
  pie_chart: ^5.4.0
  provider: ^6.1.2
  shared_preferences: ^2.3.3
  smooth_page_indicator: ^1.2.0+3
  sqflite: ^2.4.1
  table_calendar: ^3.1.2
  url_launcher: ^6.3.1
  uuid: ^4.5.1


flutter:
  uses-material-design: true

  
  assets:
    - assets/
    - assets/fonts/
    - assets/icons/
    - assets/logos/
    - assets/images/
    - assets/images/on_boarding_images/
    - assets/images/animations/

  
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Light.ttf
          weight: 300
        - asset: assets/fonts/Poppins-Regular.ttf
          weight: 400
        - asset: assets/fonts/Poppins-Italic.ttf
          style: italic
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-MediumItalic.ttf
          weight: 500
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 800


